### ISSUE TITLE
Cirrus specific output/details in all episodes

### ISSUE THREAD

**Issue by kathryn-garside** [NclRSE-Training/hpc-intro-cirrus#4]
Update episode references to HPC system from Graham to Cirrus. Update output boxes and code/scripts etc.

Make sure to describe what a general approach on other systems might look like.

- [x] Setup
- [x] Episode 1
- [x] Episode 2
- [x] Episode 3
- [x] Episode 4
- [x] Episode 5
- [x] Episode 6
- [x] Episode 7
- [x] episode 8
- [x] Episode 9

**Comment by kathryn-garside** [comment]
Edited config files with references to cirrus. Individual episodes still need checking

**Comment by Fehings** [comment]
checked through and can't see any issues, great job! Marking this as closed : )
